services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: ${TOKEN}
      APPLICATION_ID: ${APPLICATION_ID}
      DATABASE_URL: postgresql://a2itt1eb0t:botadm1n@postgres:5432/a2itt1eb0t?sslmode=disable
      TIMEZONE: ${TIMEZONE:-UTC}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: a2itt1eb0t
      POSTGRES_USER: a2itt1eb0t
      POSTGRES_PASSWORD: botadm1n
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: